INSERT INTO Album (AlbumId, Title, ArtistId, Name)
VALUES
( 1, "For Those About To Rock We Salute You", 1, "AC/DC"),
( 2, "Balls to the Wall", 2, "Accept"),
( 3, "Restless and Wild", 2, "Accept"),
( 4, "Let There Be Rock", 1, "AC/DC"),
( 5, "Big Ones", 3, "Aerosmith"),
( 6, "Jagged Little Pill", 4, "Alanis Morissette"),
( 7, "Facelift", 5, "Alice In Chains"),
( 8, "Warner 25 Anos", 6, "Antônio Carlos Jobim"),
( 9, "Plays Metallica By Four Cellos", 7, "Apocalyptica"),
( 10, "Audioslave", 8, "Audioslave"),
( 11, "Out Of Exile", 8, "Audioslave"),
( 12, "BackBeat Soundtrack", 9, "BackBeat"),
( 13, "The Best Of Billy Cobham", 10, "Billy Cobham"),
( 14, "Alcohol Fueled Brewtality Live! [Disc 1]", 11, "Black Label Society"),
( 15, "Alcohol Fueled Brewtality Live! [Disc 2]", 11, "Black Label Society"),
( 16, "Black Sabbath", 12, "Black Sabbath"),
( 17, "Black Sabbath Vol. 4 (Remaster),", 12, "Black Sabbath"),
( 18, "Body Count", 13, "Body Count"),
( 19, "Chemical Wedding", 14, "Bruce Dickinson"),
( 20, "The Best Of Buddy Guy - The Millenium Collection", 15, "Buddy Guy"),
( 21, "Prenda Minha", 16, "Caetano Veloso"),
( 22, "Sozinho Remix Ao Vivo", 16, "Caetano Veloso"),
( 23, "Minha Historia", 17, "Chico Buarque"),
( 24, "Afrociberdelia", 18, "Chico Science & Nação Zumbi"),
( 25, "Da Lama Ao Caos", 18, "Chico Science & Nação Zumbi"),
( 26, "Acústico MTV [Live]", 19, "Cidade Negra"),
( 27, "Cidade Negra - Hits", 19, "Cidade Negra"),
( 28, "Na Pista", 20, "Cláudio Zoli"),
( 29, "Axé Bahia 2001", 21, "Various Artists"),
( 30, "BBC Sessions [Disc 1] [Live]", 22, "Led Zeppelin"),
( 31, "Bongo Fury", 23, "Frank Zappa & Captain Beefheart"),
( 32, "Carnaval 2001", 21, "Various Artists"),
( 33, "Chill: Brazil (Disc 1),", 24, "Marcos Valle"),
( 34, "Chill: Brazil (Disc 2),", 6, "Antônio Carlos Jobim"),
( 35, "Garage Inc. (Disc 1),", 50, "Metallica"),
( 36, "Greatest Hits II", 51, "Queen"),
( 37, "Greatest Kiss", 52, "Kiss"),
( 38, "Heart of the Night", 53, "Spyro Gyra"),
( 39, "International Superhits", 54, "Green Day"),
( 40, "Into The Light", 55, "David Coverdale"),
( 41, "Meus Momentos", 56, "Gonzaguinha"),
( 42, "Minha História", 57, "Os Mutantes"),
( 43, "MK III The Final Concerts [Disc 1]", 58, "Deep Purple"),
( 44, "Physical Graffiti [Disc 1]", 22, "Led Zeppelin"),
( 45, "Sambas De Enredo 2001", 21, "Various Artists"),
( 46, "Supernatural", 59, "Santana"),
( 47, "The Best of Ed Motta", 37, "Ed Motta"),
( 48, "The Essential Miles Davis [Disc 1]", 68, "Miles Davis"),
( 49, "The Essential Miles Davis [Disc 2]", 68, "Miles Davis"),
( 50, "The Final Concerts (Disc 2),", 58, "Deep Purple");
